USE NovaCart_DB;
GO

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY
FOREIGN KEY (Category_ID)
REFERENCES PRODUCT_CATEGORY(Category_ID);
GO

ALTER TABLE PURCHASE
ADD CONSTRAINT FK_PURCHASE_STUDENT
FOREIGN KEY (Student_ID)
REFERENCES STUDENT(Student_ID);
GO

ALTER TABLE PURCHASE
ADD CONSTRAINT FK_PURCHASE_PRODUCT
FOREIGN KEY (Product_ID)
REFERENCES PRODUCT(Product_ID);
GO

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_PURCHASE
FOREIGN KEY (Purchase_ID)
REFERENCES PURCHASE(Purchase_ID);
GO

ALTER TABLE WISHLIST
ADD CONSTRAINT FK_WISHLIST_STUDENT
FOREIGN KEY (Student_ID)
REFERENCES STUDENT(Student_ID);
GO

ALTER TABLE WISHLIST
ADD CONSTRAINT FK_WISHLIST_PRODUCT
FOREIGN KEY (Product_ID)
REFERENCES PRODUCT(Product_ID);
GO